// Protobuf encode/decode for the message wire format (docs 4.4/4.5). Two layers:
//   - Content{ text: TextMessage } - the plaintext the Double Ratchet encrypts.
//   - MessageEnvelope{ ratchet_header, ratchet_ciphertext, pqxdh? } - the payload
//     Sealed Sender wraps. The ratchet header is opaque (wasm-internal bincode).
import { proto } from "@privex/protocol";

const toNum = (v: number | { toNumber(): number } | null | undefined): number =>
  v == null ? 0 : typeof v === "number" ? v : v.toNumber();

const u8 = (v: Uint8Array | null | undefined): Uint8Array => v ?? new Uint8Array(0);

// --- plaintext (Content / TextMessage) ---

/** Receipt request attached inside the encrypted payload (docs 4.10). The token is
 *  CSPRNG(32) generated by the sender; the server never sees it. */
export interface ReceiptRequestWire {
  tokenId: Uint8Array;
  requestDelivery: boolean;
  requestRead: boolean;
}

export function encodeText(body: string, sentAt: number, receipt?: ReceiptRequestWire): Uint8Array {
  return proto.privex.Content.encode({
    text: { body, sentAt },
    receiptRequest: receipt
      ? { tokenId: receipt.tokenId, requestDelivery: receipt.requestDelivery, requestRead: receipt.requestRead }
      : null,
  }).finish();
}

/** Contact REQUEST ("I want to add you"). No visible message body. */
export function encodeContactHello(sentAt: number): Uint8Array {
  return proto.privex.Content.encode({ contactHello: { sentAt } }).finish();
}

/** Contact ACCEPT (sent back to the requester so they learn they were accepted). */
export function encodeContactAccept(sentAt: number): Uint8Array {
  return proto.privex.Content.encode({ contactAccept: { sentAt } }).finish();
}

/** Delivery/read receipt (docs 4.10) — NO timestamp, no message reference beyond
 *  the token. Rides the exact same Content path as a text message. */
export function encodeReceipt(tokenId: Uint8Array, type: "delivered" | "read"): Uint8Array {
  return proto.privex.Content.encode({ receipt: { tokenId, receiptType: type } }).finish();
}

export interface DecodedText {
  body: string;
  sentAt: number;
}

export function decodeText(bytes: Uint8Array): DecodedText {
  const t = proto.privex.Content.decode(bytes).text;
  if (!t) throw new Error("message is not a text message");
  return { body: t.body ?? "", sentAt: toNum(t.sentAt) };
}

// --- file content (Content / FileMessage, docs 4.7) ---

export interface FileFields {
  filenameEnc: Uint8Array;
  mimeEnc: Uint8Array;
  totalSize: number;
  sha256: Uint8Array;
  chunkIds: string[];
  wrappedCek: Uint8Array;
  ephPub: Uint8Array;
  thumbnailEnc?: Uint8Array; // empty if none
  sentAt: number;
}

export function encodeFile(f: FileFields, receipt?: ReceiptRequestWire): Uint8Array {
  return proto.privex.Content.encode({
    file: {
      filenameEncrypted: f.filenameEnc,
      mimeTypeEncrypted: f.mimeEnc,
      totalSize: f.totalSize,
      sha256Plaintext: f.sha256,
      chunkIds: f.chunkIds,
      wrappedCek: f.wrappedCek,
      cekEphPub: f.ephPub,
      thumbnailEncrypted: f.thumbnailEnc ?? new Uint8Array(0),
      sentAt: f.sentAt,
    },
    receiptRequest: receipt
      ? { tokenId: receipt.tokenId, requestDelivery: receipt.requestDelivery, requestRead: receipt.requestRead }
      : null,
  }).finish();
}

export interface DecodedReceipt {
  tokenId: Uint8Array;
  type: "delivered" | "read";
}

/** Decode a plaintext Content into exactly one variant we handle. */
export function decodeContent(
  bytes: Uint8Array,
): {
  text?: DecodedText;
  file?: FileFields;
  contactHello?: boolean;
  contactAccept?: boolean;
  receipt?: DecodedReceipt;
  receiptRequest?: ReceiptRequestWire;
} {
  const c = proto.privex.Content.decode(bytes);
  if (c.contactHello) return { contactHello: true };
  if (c.contactAccept) return { contactAccept: true };
  if (c.receipt) {
    const t = c.receipt.receiptType === "read" ? "read" : "delivered";
    return { receipt: { tokenId: u8(c.receipt.tokenId), type: t } };
  }
  const receiptRequest: ReceiptRequestWire | undefined =
    c.receiptRequest && (c.receiptRequest.tokenId?.length ?? 0) > 0
      ? {
          tokenId: u8(c.receiptRequest.tokenId),
          requestDelivery: !!c.receiptRequest.requestDelivery,
          requestRead: !!c.receiptRequest.requestRead,
        }
      : undefined;
  if (c.text) return { text: { body: c.text.body ?? "", sentAt: toNum(c.text.sentAt) }, receiptRequest };
  if (c.file) {
    const f = c.file;
    return {
      receiptRequest,
      file: {
        filenameEnc: u8(f.filenameEncrypted),
        mimeEnc: u8(f.mimeTypeEncrypted),
        totalSize: toNum(f.totalSize),
        sha256: u8(f.sha256Plaintext),
        chunkIds: f.chunkIds ?? [],
        wrappedCek: u8(f.wrappedCek),
        ephPub: u8(f.cekEphPub),
        thumbnailEnc: f.thumbnailEncrypted && f.thumbnailEncrypted.length > 0 ? u8(f.thumbnailEncrypted) : undefined,
        sentAt: toNum(f.sentAt),
      },
    };
  }
  return {};
}

// --- transport envelope (MessageEnvelope) ---

export interface PqxdhInitWire {
  alice_ik_pub: Uint8Array;
  alice_ek_pub: Uint8Array;
  kyber_ciphertext: Uint8Array;
  opk_used: boolean;
  opk_id: number;
}

/** Cross-device sync copy (docs 4.11 Mode C) - rides MessageEnvelope INSTEAD of
 *  ratchet fields (the two devices share the link key, not a ratchet). */
export interface DeviceSyncWire {
  toDevice: Uint8Array;
  fromDevice: Uint8Array;
  blob: Uint8Array;
}

export function encodeEnvelope(
  header: Uint8Array,
  ciphertext: Uint8Array,
  pqxdh?: PqxdhInitWire,
): Uint8Array {
  return proto.privex.MessageEnvelope.encode({
    ratchetHeader: header,
    ratchetCiphertext: ciphertext,
    pqxdh: pqxdh
      ? {
          aliceIkPub: pqxdh.alice_ik_pub,
          aliceEkPub: pqxdh.alice_ek_pub,
          kyberCiphertext: pqxdh.kyber_ciphertext,
          opkUsed: pqxdh.opk_used,
          opkId: pqxdh.opk_id,
        }
      : null,
  }).finish();
}

export function encodeDeviceSyncEnvelope(sync: DeviceSyncWire): Uint8Array {
  return proto.privex.MessageEnvelope.encode({
    ratchetHeader: new Uint8Array(0),
    ratchetCiphertext: new Uint8Array(0),
    deviceSync: { toDevice: sync.toDevice, fromDevice: sync.fromDevice, blob: sync.blob },
  }).finish();
}

export interface DecodedEnvelope {
  header: Uint8Array;
  ciphertext: Uint8Array;
  pqxdh?: PqxdhInitWire;
  deviceSync?: DeviceSyncWire;
}

export function decodeEnvelope(bytes: Uint8Array): DecodedEnvelope {
  const e = proto.privex.MessageEnvelope.decode(bytes);
  const out: DecodedEnvelope = { header: u8(e.ratchetHeader), ciphertext: u8(e.ratchetCiphertext) };
  if (e.pqxdh) {
    out.pqxdh = {
      alice_ik_pub: u8(e.pqxdh.aliceIkPub),
      alice_ek_pub: u8(e.pqxdh.aliceEkPub),
      kyber_ciphertext: u8(e.pqxdh.kyberCiphertext),
      opk_used: !!e.pqxdh.opkUsed,
      opk_id: e.pqxdh.opkId ?? 0,
    };
  }
  if (e.deviceSync && (e.deviceSync.toDevice?.length ?? 0) > 0) {
    out.deviceSync = {
      toDevice: u8(e.deviceSync.toDevice),
      fromDevice: u8(e.deviceSync.fromDevice),
      blob: u8(e.deviceSync.blob),
    };
  }
  return out;
}
