#!/usr/bin/env bash
# Generate a complete Privex .env with fresh credentials.
# Usage: bash infra/scripts/generate-credentials.sh > .env
# Then add OPAQUE_SERVER_SETUP (generated by deploy.sh or gen_opaque_setup).
set -euo pipefail

DOMAIN="${PRIVEX_DOMAIN:-privex.dpdns.org}"

# 32-byte hex keys
SESSION_HMAC_KEY=$(openssl rand -hex 32)
KT_SIGNING_KEY=$(openssl rand -hex 32)
TIME_SIGNING_KEY=$(openssl rand -hex 32)

# Passwords
PG_PASS=$(openssl rand -base64 24 | tr -d /=+ | cut -c1-24)
MINIO_PASS=$(openssl rand -base64 24 | tr -d /=+ | cut -c1-24)
TURN_SECRET=$(openssl rand -hex 32)

cat <<ENV
# Privex Server — Environment Configuration
# Generated $(date)
# Add OPAQUE_SERVER_SETUP after first deploy (deploy.sh generates it).

# --- Server ---
BIND_ADDR=0.0.0.0:8888

# --- Database (PostgreSQL) ---
DATABASE_URL=postgresql://privex:${PG_PASS}@127.0.0.1:5432/privex

# --- Cache (Redis) ---
REDIS_URL=redis://127.0.0.1:6380

# --- Secrets ---
SESSION_HMAC_KEY=${SESSION_HMAC_KEY}
KT_SIGNING_KEY=${KT_SIGNING_KEY}
TIME_SIGNING_KEY=${TIME_SIGNING_KEY}
OPAQUE_SERVER_SETUP=

# --- Proof-of-Work ---
POW_DIFFICULTY=22
# Argon2id hybrid Layer-2 PoW (docs 8.5.1). Default ON (unset = enabled);
# "false" is the emergency rollback only.
POW_ARGON2_ENABLED=true

# --- WebSocket ---
WS_PING_SECS=30

# --- Object storage (MinIO) ---
R2_BUCKET=privex-files
R2_ENDPOINT=http://127.0.0.1:9000
R2_REGION=us-east-1
R2_ACCESS_KEY=privex
R2_SECRET_KEY=${MINIO_PASS}

# --- File uploads ---
FILE_UPLOADS_ENABLED=true

# --- TURN relay (optional Phase 1) ---
TURN_SECRET=${TURN_SECRET}

# --- CORS ---
CORS_ORIGIN=https://${DOMAIN}
WS_ALLOWED_ORIGINS=https://${DOMAIN}

# --- Docker infrastructure passwords ---
POSTGRES_PASSWORD=${PG_PASS}
MINIO_PASSWORD=${MINIO_PASS}
MINIO_ROOT_PASSWORD=${MINIO_PASS}
ENV
